import { getDb } from '../server/db';
import { mealPrepRecipes } from '../drizzle/schema';

const expandedMeals = [
  // PRE-WORKOUT (7 AM) - 5 options
  {
    name: 'Banana with Almond Butter',
    description: 'Quick energy source, easy to digest before training',
    category: 'pre-workout' as const,
    caloriesPerServing: 280,
    carbs: 35,
    protein: 10,
    fats: 12,
    servingSize: '1 medium banana + 2 tbsp almond butter',
    prepTime: 2,
    cookTime: 0,
    ingredients: 'Banana, almond butter',
    instructions: 'Slice banana and serve with almond butter on the side for dipping.',
  },
  {
    name: 'Oatmeal with Honey',
    description: 'Sustained energy with quick carbs and fiber',
    category: 'pre-workout' as const,
    caloriesPerServing: 320,
    carbs: 52,
    protein: 8,
    fats: 6,
    servingSize: '1 cup cooked oatmeal + 1 tbsp honey',
    prepTime: 5,
    cookTime: 5,
    ingredients: 'Rolled oats, honey, water',
    instructions: 'Cook oats according to package directions. Top with honey.',
  },
  {
    name: 'Toast with Jam',
    description: 'Simple carbs for quick energy',
    category: 'pre-workout' as const,
    caloriesPerServing: 250,
    carbs: 48,
    protein: 7,
    fats: 3,
    servingSize: '2 slices whole wheat toast + 2 tbsp jam',
    prepTime: 3,
    cookTime: 2,
    ingredients: 'Whole wheat bread, jam',
    instructions: 'Toast bread and spread jam evenly on both slices.',
  },
  {
    name: 'Greek Yogurt with Granola',
    description: 'Protein and carbs for sustained energy',
    category: 'pre-workout' as const,
    caloriesPerServing: 300,
    carbs: 42,
    protein: 15,
    fats: 7,
    servingSize: '1 cup Greek yogurt + 1/4 cup granola',
    prepTime: 2,
    cookTime: 0,
    ingredients: 'Greek yogurt, granola',
    instructions: 'Pour yogurt into bowl and top with granola.',
  },
  {
    name: 'Rice Cakes with Honey',
    description: 'Light, digestible carbs before training',
    category: 'pre-workout' as const,
    caloriesPerServing: 220,
    carbs: 45,
    protein: 4,
    fats: 2,
    servingSize: '3 rice cakes + 1 tbsp honey',
    prepTime: 2,
    cookTime: 0,
    ingredients: 'Rice cakes, honey',
    instructions: 'Arrange rice cakes on plate and drizzle with honey.',
  },

  // POST-WORKOUT (After Training) - 5 options
  {
    name: 'Chicken Breast with Rice',
    description: 'High protein recovery with quick carbs',
    category: 'post-workout' as const,
    caloriesPerServing: 450,
    carbs: 55,
    protein: 45,
    fats: 4,
    servingSize: '6 oz grilled chicken + 1 cup white rice',
    prepTime: 20,
    cookTime: 20,
    ingredients: 'Chicken breast, white rice, salt, pepper',
    instructions: 'Grill chicken until cooked through. Cook rice according to package directions.',
  },
  {
    name: 'Protein Smoothie',
    description: 'Fast-absorbing protein and carbs for recovery',
    category: 'post-workout' as const,
    caloriesPerServing: 380,
    carbs: 48,
    protein: 35,
    fats: 5,
    servingSize: '1 scoop protein powder + 1 banana + 1 cup milk',
    prepTime: 3,
    cookTime: 0,
    ingredients: 'Protein powder, banana, milk',
    instructions: 'Blend protein powder, banana, and milk until smooth.',
  },
  {
    name: 'Turkey Sandwich',
    description: 'Convenient recovery meal with protein and carbs',
    category: 'post-workout' as const,
    caloriesPerServing: 420,
    carbs: 45,
    protein: 38,
    fats: 8,
    servingSize: '6 oz turkey + 2 slices whole wheat bread + veggies',
    prepTime: 5,
    cookTime: 0,
    ingredients: 'Turkey slices, whole wheat bread, lettuce, tomato',
    instructions: 'Assemble sandwich with turkey, lettuce, and tomato between bread slices.',
  },
  {
    name: 'Egg Scramble with Toast',
    description: 'Complete recovery meal with quality protein',
    category: 'post-workout' as const,
    caloriesPerServing: 400,
    carbs: 40,
    protein: 32,
    fats: 12,
    servingSize: '3 eggs + 2 slices toast + butter',
    prepTime: 10,
    cookTime: 10,
    ingredients: 'Eggs, whole wheat bread, butter, salt, pepper',
    instructions: 'Scramble eggs in butter until cooked. Toast bread and serve together.',
  },
  {
    name: 'Tuna with Sweet Potato',
    description: 'Lean protein with nutrient-dense carbs',
    category: 'post-workout' as const,
    caloriesPerServing: 380,
    carbs: 50,
    protein: 40,
    fats: 3,
    servingSize: '5 oz canned tuna + 1 medium sweet potato',
    prepTime: 15,
    cookTime: 15,
    ingredients: 'Canned tuna, sweet potato, olive oil',
    instructions: 'Bake sweet potato at 400°F for 15 minutes. Mix tuna with olive oil.',
  },

  // LUNCH (3 PM) - 5 options
  {
    name: 'Grilled Chicken with Quinoa',
    description: 'Complete meal with lean protein and complete carbs',
    category: 'lunch' as const,
    caloriesPerServing: 520,
    carbs: 58,
    protein: 48,
    fats: 8,
    servingSize: '7 oz grilled chicken + 1 cup cooked quinoa + veggies',
    prepTime: 25,
    cookTime: 25,
    ingredients: 'Chicken breast, quinoa, broccoli, olive oil',
    instructions: 'Grill chicken and cook quinoa. Steam broccoli and toss with olive oil.',
  },
  {
    name: 'Beef Steak with Potatoes',
    description: 'Iron-rich protein with satisfying carbs',
    category: 'lunch' as const,
    caloriesPerServing: 580,
    carbs: 52,
    protein: 50,
    fats: 14,
    servingSize: '6 oz steak + 1 medium baked potato + veggies',
    prepTime: 30,
    cookTime: 30,
    ingredients: 'Beef steak, potato, olive oil, salt, pepper',
    instructions: 'Bake potato at 400°F. Grill steak to desired doneness.',
  },
  {
    name: 'Turkey Meatballs with Pasta',
    description: 'Lean protein with quick-digesting carbs',
    category: 'lunch' as const,
    caloriesPerServing: 510,
    carbs: 60,
    protein: 42,
    fats: 8,
    servingSize: '6 oz turkey meatballs + 1.5 cups pasta + sauce',
    prepTime: 20,
    cookTime: 20,
    ingredients: 'Ground turkey, pasta, tomato sauce, herbs',
    instructions: 'Bake meatballs at 375°F. Cook pasta and mix with sauce.',
  },
  {
    name: 'Salmon with Rice and Veggies',
    description: 'Omega-3 rich protein with complete carbs',
    category: 'lunch' as const,
    caloriesPerServing: 540,
    carbs: 55,
    protein: 45,
    fats: 12,
    servingSize: '5 oz salmon + 1 cup rice + mixed veggies',
    prepTime: 25,
    cookTime: 25,
    ingredients: 'Salmon fillet, brown rice, broccoli, olive oil',
    instructions: 'Bake salmon at 400°F. Cook brown rice. Steam broccoli.',
  },
  {
    name: 'Chicken Burrito Bowl',
    description: 'Satisfying meal with balanced macros',
    category: 'lunch' as const,
    caloriesPerServing: 530,
    carbs: 62,
    protein: 44,
    fats: 10,
    servingSize: '6 oz chicken + 1 cup rice + beans + veggies',
    prepTime: 20,
    cookTime: 20,
    ingredients: 'Chicken, rice, black beans, corn, salsa, avocado',
    instructions: 'Grill chicken. Layer rice, beans, corn, chicken, and toppings in bowl.',
  },

  // SNACKS - 5 options
  {
    name: 'Apple with Peanut Butter',
    description: 'Quick energy with sustained carbs and protein',
    category: 'snack' as const,
    caloriesPerServing: 220,
    carbs: 28,
    protein: 8,
    fats: 9,
    servingSize: '1 medium apple + 1 tbsp peanut butter',
    prepTime: 2,
    cookTime: 0,
    ingredients: 'Apple, peanut butter',
    instructions: 'Slice apple and serve with peanut butter for dipping.',
  },
  {
    name: 'Protein Bar',
    description: 'Convenient on-the-go snack',
    category: 'snack' as const,
    caloriesPerServing: 250,
    carbs: 30,
    protein: 20,
    fats: 8,
    servingSize: '1 protein bar',
    prepTime: 0,
    cookTime: 0,
    ingredients: 'Protein bar (store-bought)',
    instructions: 'Unwrap and eat.',
  },
  {
    name: 'Mixed Nuts and Dried Fruit',
    description: 'Energy-dense snack for sustained fuel',
    category: 'snack' as const,
    caloriesPerServing: 280,
    carbs: 32,
    protein: 9,
    fats: 14,
    servingSize: '1/4 cup mixed nuts + 1/4 cup dried fruit',
    prepTime: 0,
    cookTime: 0,
    ingredients: 'Mixed nuts, dried fruit',
    instructions: 'Mix nuts and dried fruit in a bowl or bag.',
  },
  {
    name: 'Cottage Cheese with Berries',
    description: 'High protein snack with antioxidants',
    category: 'snack' as const,
    caloriesPerServing: 200,
    carbs: 18,
    protein: 25,
    fats: 4,
    servingSize: '1 cup cottage cheese + 1/2 cup berries',
    prepTime: 2,
    cookTime: 0,
    ingredients: 'Cottage cheese, mixed berries',
    instructions: 'Pour cottage cheese into bowl and top with berries.',
  },
  {
    name: 'Energy Balls',
    description: 'Homemade snack with oats and nut butter',
    category: 'snack' as const,
    caloriesPerServing: 240,
    carbs: 28,
    protein: 8,
    fats: 11,
    servingSize: '3 energy balls',
    prepTime: 15,
    cookTime: 0,
    ingredients: 'Oats, peanut butter, honey, dark chocolate chips',
    instructions: 'Mix oats, peanut butter, honey, and chocolate chips. Roll into balls and refrigerate.',
  },

  // DINNER (6 PM) - 5 options
  {
    name: 'Slow Cooker Chicken with Veggies',
    description: 'Tender, flavorful, minimal effort meal prep',
    category: 'dinner' as const,
    caloriesPerServing: 480,
    carbs: 48,
    protein: 52,
    fats: 8,
    servingSize: '8 oz chicken + 1.5 cups veggies + 1/2 cup sauce',
    prepTime: 10,
    cookTime: 240,
    ingredients: 'Chicken breast, carrots, celery, onion, broth',
    instructions: 'Add all ingredients to slow cooker and cook on low for 4 hours.',
  },
  {
    name: 'Air Fryer Steak with Sweet Potato',
    description: 'Quick, crispy steak with nutrient-dense carbs',
    category: 'dinner' as const,
    caloriesPerServing: 520,
    carbs: 50,
    protein: 48,
    fats: 12,
    servingSize: '6 oz steak + 1 medium sweet potato + veggies',
    prepTime: 5,
    cookTime: 15,
    ingredients: 'Beef steak, sweet potato, olive oil, seasoning',
    instructions: 'Air fry steak at 400°F for 12-15 minutes. Bake sweet potato separately.',
  },
  {
    name: 'Turkey Chili',
    description: 'Hearty, protein-packed meal with fiber',
    category: 'dinner' as const,
    caloriesPerServing: 450,
    carbs: 48,
    protein: 44,
    fats: 8,
    servingSize: '1.5 cups turkey chili',
    prepTime: 10,
    cookTime: 30,
    ingredients: 'Ground turkey, beans, tomatoes, peppers, spices',
    instructions: 'Brown turkey, add beans and tomatoes, simmer for 30 minutes.',
  },
  {
    name: 'Baked Salmon with Rice and Broccoli',
    description: 'Omega-3 rich with complete nutrition',
    category: 'dinner' as const,
    caloriesPerServing: 510,
    carbs: 52,
    protein: 46,
    fats: 11,
    servingSize: '6 oz salmon + 1 cup rice + 1.5 cups broccoli',
    prepTime: 10,
    cookTime: 25,
    ingredients: 'Salmon fillet, brown rice, broccoli, olive oil, lemon',
    instructions: 'Bake salmon at 400°F for 12-15 minutes. Cook rice and steam broccoli.',
  },
  {
    name: 'Grilled Chicken Pasta',
    description: 'Satisfying dinner with balanced macros',
    category: 'dinner' as const,
    caloriesPerServing: 540,
    carbs: 62,
    protein: 48,
    fats: 9,
    servingSize: '7 oz chicken + 1.5 cups pasta + marinara sauce',
    prepTime: 10,
    cookTime: 20,
    ingredients: 'Chicken breast, pasta, tomato sauce, garlic, herbs',
    instructions: 'Grill chicken. Cook pasta and mix with marinara sauce.',
  },
];

async function seedMeals() {
  try {
    const db = await getDb();
    if (!db) {
      console.error('❌ Database connection failed');
      process.exit(1);
    }

    // Delete existing meals to avoid duplicates
    await db.delete(mealPrepRecipes);

    // Insert all meals
    for (const meal of expandedMeals) {
      await db.insert(mealPrepRecipes).values({
        name: meal.name,
        description: meal.description,
        category: meal.category,
        caloriesPerServing: meal.caloriesPerServing,
        carbs: meal.carbs,
        protein: meal.protein,
        fats: meal.fats,
        servingSize: meal.servingSize,
        prepTime: meal.prepTime,
        cookTime: meal.cookTime,
        ingredients: meal.ingredients,
        instructions: meal.instructions,
      });
    }

    console.log(`✅ Successfully seeded ${expandedMeals.length} meal recipes`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding meals:', error);
    process.exit(1);
  }
}

seedMeals();
